---
# role: pve
# file: tasks/facts.yml

- name: "PVE | Set base detection facts"
  ansible.builtin.set_fact:
    __pve_is_container: "{{ __pve_virtualization_type in __pve_container_types }}"
  vars:
    __pve_virtualization_type: "{{ ansible_facts['virtualization_type'] | default('') }}"
