---
# role: pve
# file: tasks/ha.yml

- name: "PVE | Manage HA services"
  when: not __pve_is_container | bool
  block:
    - name: "PVE | Stop, disable and mask HA services"
      ansible.builtin.systemd_service:
        name: "{{ item.key }}"
        state: stopped
        enabled: false
        masked: true
      loop: "{{ pve_ha_services | default({}) | dict2items }}"
      when:
        - not (item.value | bool)

    - name: "PVE | Unmask, enable and start HA services"
      ansible.builtin.systemd_service:
        name: "{{ item.key }}"
        state: started
        masked: false
        enabled: true
      loop: "{{ pve_ha_services | default({}) | dict2items }}"
      when:
        - item.value | bool
