---
# role: pve
# file: tasks/ha.yml

- name: "PVE | Skip HA service management when PVE is not detected"
  ansible.builtin.debug:
    msg: "Skipping PVE HA service management because Proxmox VE was not detected."
  when: not __pve_detected | bool

- name: "PVE | Manage HA services"
  when: __pve_detected | bool
  block:
    - name: "PVE | Stop, disable, and mask HA services"
      ansible.builtin.systemd_service:
        name: "{{ item.key }}"
        state: stopped
        enabled: false
        masked: true
      loop: "{{ pve_ha_services | default({}) | dict2items }}"
      when:
        - not (item.value | bool)
        - item.key in (__pve_service_names | default([]))

    - name: "PVE | Unmask HA services"
      ansible.builtin.systemd_service:
        name: "{{ item.key }}"
        masked: false
      loop: "{{ pve_ha_services | default({}) | dict2items }}"
      when:
        - item.value | bool
        - item.key in (__pve_service_names | default([]))

    - name: "PVE | Enable HA services"
      ansible.builtin.systemd_service:
        name: "{{ item.key }}"
        enabled: true
      loop: "{{ pve_ha_services | default({}) | dict2items }}"
      when:
        - item.value | bool
        - item.key in (__pve_service_names | default([]))
