---
# role: pve
# file: tasks/install.yml

- name: "PVE | Install Proxmox VE on real hosts"
  when: not __pve_is_container | bool
  block:
    - name: "PVE | Install Proxmox VE kernel"
      ansible.builtin.apt:
        name: "{{ __pve_install_kernel_packages }}"
        state: present
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: __pve_install_kernel
      notify:
        - pve reboot into proxmox kernel
        - pve refresh facts after proxmox kernel reboot

    - name: "PVE | Flush Proxmox VE kernel handlers"
      ansible.builtin.meta: flush_handlers

    - name: "PVE | Assert Proxmox VE kernel is running"
      ansible.builtin.assert:
        that:
          - "'-pve' in ansible_facts.kernel"
        fail_msg: >-
          The Proxmox VE kernel is installed but not running. Boot into the Proxmox VE kernel before installing the
          remaining Proxmox VE package set.

    - name: "PVE | Preseed Postfix mailer type"
      ansible.builtin.debconf:
        name: postfix
        question: postfix/main_mailer_type
        value: "Local only"
        vtype: select

    - name: "PVE | Preseed Postfix mailname"
      ansible.builtin.debconf:
        name: postfix
        question: postfix/mailname
        value: "{{ ansible_facts.fqdn | default(inventory_hostname) }}"
        vtype: string

    - name: "PVE | Install Proxmox VE package set"
      ansible.builtin.apt:
        name: "{{ __pve_install_packages }}"
        state: present
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: "PVE | Remove Debian kernel and boot scanner packages"
      ansible.builtin.apt:
        name: >-
          {{ __pve_debian_kernel_absent_packages[ansible_facts.distribution_release]
          + __pve_boot_absent_packages }}
        state: absent
      notify: pve update grub
