---
# role: pve
# file: tasks/repository.yml

- name: "PVE | Ensure APT source directory exists"
  ansible.builtin.file:
    path: "{{ __pve_no_subscription_sources_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "PVE | Ensure APT keyring directory exists"
  ansible.builtin.file:
    path: "{{ __pve_proxmox_apt_keyring_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "PVE | Install Proxmox VE APT keyring"
  ansible.builtin.get_url:
    url: "{{ __pve_proxmox_apt_keyrings[ansible_facts.distribution_release].url }}"
    dest: "{{ __pve_proxmox_apt_keyring_path }}"
    checksum: "{{ __pve_proxmox_apt_keyrings[ansible_facts.distribution_release].checksum }}"
    owner: root
    group: root
    mode: "0644"
  when: not __pve_is_container | bool

- name: "PVE | Remove conflicting Proxmox VE repository list sources"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ __pve_conflicting_repository_source_paths }}"

- name: "PVE | Disable Proxmox VE enterprise repository"
  ansible.builtin.import_tasks: enterprise.yml

- name: "PVE | Enable Proxmox VE no-subscription repository"
  ansible.builtin.copy:
    dest: "{{ __pve_no_subscription_sources_path }}"
    owner: root
    group: root
    mode: "0644"
    content: |
      Types: deb
      URIs: {{ __pve_no_subscription_repository_uri }}
      Suites: {{ ansible_facts.distribution_release }}
      Components: {{ __pve_no_subscription_repository_component }}
      Signed-By: {{ __pve_proxmox_apt_keyring_path }}
      Enabled: yes
