---
# role: pve
# file: tasks/hardening/packages.yml

- name: "PVE | Remove installed unsafe legacy packages"
  ansible.builtin.package:
    name: "{{ __pve_hardening_absent_packages }}"
    state: absent
