---
# role: pve
# file: molecule/resources/playbooks/verify.yml

- name: "Molecule | verify container | pve"
  hosts: all
  gather_facts: true
  tasks:
    - name: "PVE | Query failed systemd services"
      ansible.builtin.command:
        argv:
          - systemctl
          - list-units
          - --type=service
          - --state=failed
          - --no-legend
          - --plain
      register: __pve_verify_failed_services
      changed_when: false
      failed_when: __pve_verify_failed_services.stdout != ""
